@host = http://localhost:3000

#################
#################
#################
################# API AUTORES
GET {{host}}/api/autores






#################
#################
#################
################# API ARTICULOS
GET {{host}}/api/articulos