@host = http://localhost:3000

#################
#################
#################
################# API AUTORES
GET {{host}}/api/autores

###
GET {{host}}/api/autores/4

###
POST {{host}}/api/autores
Content-Type: application/json

{
    "nombre": "Autor de prueba",
    "email": "email de prueba2",
    "imagen": "https://"
}


#################
#################
#################
################# API ARTICULOS
GET {{host}}/api/articulos

###
GET {{host}}/api/articulos/3

###
GET {{host}}/api/articulos/autor/3

###
POST {{host}}/api/articulos
Content-Type: application/json

{
    "titulo": "Titulo de prueba",
    "descripcion": "Descripción de un artículo de prueba",
    "categoria": "Entrevistas",
    "autores_id":3
}